kind: Deployment
apiVersion: apps/v1
metadata:
  name: coffeeshop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: coffeeshop-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: coffeeshop-ui
    spec:
      containers:
        - name: app
          image: 'ianpartridge/coffeeshop-ui:latest'
          ports:
            - name: 8080-tcp
              containerPort: 8080
              protocol: TCP
          env:
            - name: MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.coffeeshop.svc:9092
          imagePullPolicy: IfNotPresent
